baseURL = "https://pixambi.github.io/pixam-blog/"
languageCode = 'en-us'
title = 'Pixam'

pagination.pagerSize = 2

[params]
    dateFormat = "Jan 2, 2006"

[taxonomies]
    author = "authors"
    category = "categories"
